module.exports = {
  docs: [
    'index',
    'getting-started',
    'donate',
      {
          type: 'category',
          label: 'Features',
          link: {
              type: 'generated-index',
              title: 'Features',
              slug: '/features',
              keywords: ['features'],
          },
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'features',
              },
          ],
      },
      {
          type: 'category',
          label: 'Others',
          link: {
              type: 'generated-index',
              title: 'Others',
              slug: '/others',
              keywords: ['others'],
          },
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others',
              },
          ],
      },

  ],
};
