module.exports = {
    community: [
        'index',
        {
            type: 'category',
            label: 'FAQ & Troubleshooting',
            link: {
                type: 'generated-index',
                title: 'FAQ & Troubleshooting',
                slug: '/faq',
                keywords: ['faq', 'troubleshooting'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'faq',
                },
            ],
        },
    ]
  };
  