/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "No Name Studio",
  "tagline": "No Name Studio VN",
  "url": "http://www.nnsvn.me",
  "staticDirectories": [
    "static"
  ],
  "favicon": "img/favicon.png",
  "baseUrl": "/",
  "organizationName": "manhbi18112005",
  "projectName": "bot-docs-website",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "customFields": {
    "markdownOptions": {
      "html": true
    },
    "gaGtag": true,
    "repoUrl": "https://github.com/manhbi18112005"
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "sidebarPath": "./sidebarsDocs.js",
          "rehypePlugins": [
            null
          ],
          "disableVersioning": true
        },
        "blog": {
          "blogTitle": "No Name Bot Blog",
          "blogDescription": "Get the latest news about No Name Bot",
          "postsPerPage": 15,
          "blogSidebarTitle": "All posts",
          "blogSidebarCount": "ALL",
          "showReadingTime": true,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2023 No Name Studio."
          }
        },
        "theme": {
          "customCss": "C:\\Users\\ASUS_ROG\\Downloads\\New-Website\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": []
      }
    ],
    [
      "docusaurus-gtm-plugin",
      {
        "id": "GTM-TXF92FT"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "sidebarPath": "C:\\Users\\ASUS_ROG\\Downloads\\New-Website\\sidebarsCommunity.js"
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      }
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "No Name Studio",
      "logo": {
        "alt": "No Name Studio Logo",
        "src": "img/title.png",
        "srcDark": "img/title.png"
      },
      "items": [
        {
          "to": "docs",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "News",
          "position": "left"
        },
        {
          "to": "community",
          "label": "Community",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "left",
          "dropdownItemsAfter": [
            {
              "href": "https://en.bot.nnsvn.me",
              "label": "EN"
            },
            {
              "href": "https://vn.bot.nnsvn.me",
              "label": "VI"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://github.com/manhbi18112005/New-Website",
          "label": "GitHub",
          "title": "View on GitHub",
          "position": "right",
          "className": "icon"
        },
        {
          "href": "https://discord.com/invite/nCQbSag",
          "label": "Discord",
          "title": "Chat on Discord",
          "position": "right",
          "className": "icon"
        },
        {
          "href": "https://botapp.nnsvn.me/dashboard",
          "label": "Dashboard",
          "title": "No Name Bot Main App",
          "position": "right",
          "className": "icon"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Guides",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "Careers",
              "href": "mailto:myt@nonamestudip.xyz"
            },
            {
              "label": "Privacy Policy",
              "to": "/privacy"
            },
            {
              "label": "Terms of use",
              "to": "/term"
            }
          ]
        },
        {
          "title": "Contact us",
          "items": [
            {
              "label": "Email",
              "href": "mailto:support.team@nnsvn.me"
            },
            {
              "label": "Github",
              "href": "https://github.com/No-Name-Studio-VN"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/nonamestudiovn"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/nCQbSag"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 No Name Studio"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "prism": {
      "defaultLanguage": "typescript",
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "docker",
        "log"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
